import "@/app/_styles/globals.css";
import { Libre_Baskerville } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Libre_Baskerville({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={font.className}>
      <body>{children}</body>
    </html>
  );
}
